//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Amul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class amuladdress
    {
        public string orderid { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string email { get; set; }
        public string contactno { get; set; }
    }
}
