//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Amul.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class amuladdproduct
    {
        public int productid { get; set; }
        public string productname { get; set; }
        public string productimage { get; set; }

        internal static object where(Func<object, bool> p)
        {
            throw new NotImplementedException();
        }

        public int price { get; set; }
        public string description { get; set; }
        public string quantity { get; set; }
        public string categoryname { get; set; }
        public string available { get; set; }
        public string soldout { get; set; }
    }
}
