//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Amul.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentEntities3 : DbContext
    {
        public StudentEntities3()
            : base("name=StudentEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amuladdtocart> amuladdtocarts { get; set; }
        public virtual DbSet<amulmilkproduct> amulmilkproducts { get; set; }
        public virtual DbSet<amuladdress> amuladdresses { get; set; }
        public virtual DbSet<amulorderdetail> amulorderdetails { get; set; }
    }
}
